version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data:
